import type {
  KPIData,
  SEOInsight,
  KeywordData,
  RankData,
  CompetitorData,
  ReportData,
  UserSettings,
  SubscriptionData,
  AdminUser,
  AdminSubscription,
  AnalyticsData,
  NotificationData,
  SEOAnalysisHistory,
  KeywordResearchHistory,
  RankCheckHistory,
} from '../types';

export const mockKPIData: KPIData[] = [
  {
    id: '1',
    label: 'Organic Traffic',
    value: '45.2K',
    change: 12.5,
    changeLabel: 'vs last month',
    trend: 'up',
    icon: 'Users',
  },
  {
    id: '2',
    label: 'Average Position',
    value: '14.3',
    change: -2.1,
    changeLabel: 'vs last month',
    trend: 'down',
    icon: 'Target',
  },
  {
    id: '3',
    label: 'Keywords Tracked',
    value: '1,284',
    change: 8.3,
    changeLabel: 'vs last month',
    trend: 'up',
    icon: 'Key',
  },
  {
    id: '4',
    label: 'Backlinks',
    value: '8,432',
    change: 15.7,
    changeLabel: 'vs last month',
    trend: 'up',
    icon: 'Link',
  },
];

export const mockSEOInsights: SEOInsight[] = [
  {
    id: '1',
    type: 'issue',
    title: 'Missing Meta Descriptions',
    description: '23 pages are missing meta descriptions, which can impact click-through rates.',
    severity: 'warning',
    metric: 'Pages Affected',
    metricValue: '23',
  },
  {
    id: '2',
    type: 'opportunity',
    title: 'High-Volume Keywords',
    description: '5 keywords have search volume over 10K but low competition scores.',
    severity: 'info',
    metric: 'Opportunities',
    metricValue: '5',
  },
  {
    id: '3',
    type: 'success',
    title: 'Page Speed Improved',
    description: 'Core Web Vitals scores improved across all monitored pages.',
    severity: 'info',
    metric: 'Avg Score',
    metricValue: '92/100',
  },
  {
    id: '4',
    type: 'issue',
    title: 'Broken Links Detected',
    description: '8 broken internal links found that need immediate attention.',
    severity: 'critical',
    metric: 'Links Broken',
    metricValue: '8',
  },
  {
    id: '5',
    type: 'opportunity',
    title: 'Image Alt Text Missing',
    description: '47 images are missing alt text, affecting accessibility and SEO.',
    severity: 'warning',
    metric: 'Images',
    metricValue: '47',
  },
];

export const mockKeywords: KeywordData[] = [
  {
    id: '1',
    keyword: 'seo optimization tools',
    volume: 12400,
    difficulty: 45,
    cpc: 2.5,
    competition: 'medium',
    trend: 'up',
    suggestions: ['best seo tools', 'seo optimization software'],
  },
  {
    id: '2',
    keyword: 'keyword research',
    volume: 33100,
    difficulty: 52,
    cpc: 4.2,
    competition: 'high',
    trend: 'stable',
    suggestions: ['keyword research tool', 'free keyword research'],
  },
  {
    id: '3',
    keyword: 'backlink checker',
    volume: 8100,
    difficulty: 38,
    cpc: 3.1,
    competition: 'medium',
    trend: 'up',
    suggestions: ['free backlink checker', 'backlink analysis'],
  },
  {
    id: '4',
    keyword: 'rank tracking software',
    volume: 5400,
    difficulty: 41,
    cpc: 5.8,
    competition: 'low',
    trend: 'down',
    suggestions: ['serp rank tracker', 'google rank checker'],
  },
  {
    id: '5',
    keyword: 'site audit tool',
    volume: 6600,
    difficulty: 35,
    cpc: 3.9,
    competition: 'low',
    trend: 'up',
    suggestions: ['website audit', 'seo audit tool'],
  },
  {
    id: '6',
    keyword: 'competitor analysis',
    volume: 9900,
    difficulty: 48,
    cpc: 4.5,
    competition: 'medium',
    trend: 'stable',
    suggestions: ['competitor research', 'competitive analysis tools'],
  },
];

export const mockRankData: RankData[] = [
  {
    id: '1',
    keyword: 'seo optimization tools',
    currentRank: 4,
    previousRank: 6,
    url: 'https://example.com/seo-tools',
    searchVolume: 12400,
    lastUpdated: '2024-01-15',
  },
  {
    id: '2',
    keyword: 'keyword research',
    currentRank: 12,
    previousRank: 15,
    url: 'https://example.com/keyword-research',
    searchVolume: 33100,
    lastUpdated: '2024-01-15',
  },
  {
    id: '3',
    keyword: 'backlink checker',
    currentRank: 8,
    previousRank: 8,
    url: 'https://example.com/backlink-checker',
    searchVolume: 8100,
    lastUpdated: '2024-01-15',
  },
  {
    id: '4',
    keyword: 'rank tracking software',
    currentRank: 18,
    previousRank: 22,
    url: 'https://example.com/rank-tracker',
    searchVolume: 5400,
    lastUpdated: '2024-01-15',
  },
  {
    id: '5',
    keyword: 'site audit tool',
    currentRank: 6,
    previousRank: 9,
    url: 'https://example.com/site-audit',
    searchVolume: 6600,
    lastUpdated: '2024-01-15',
  },
];

export const mockCompetitors: CompetitorData[] = [
  {
    id: '1',
    domain: 'competitor1.com',
    domainAuthority: 68,
    backlinks: 45200,
    organicKeywords: 28500,
    organicTraffic: 125000,
    overlapScore: 78,
  },
  {
    id: '2',
    domain: 'competitor2.com',
    domainAuthority: 72,
    backlinks: 67100,
    organicKeywords: 41200,
    organicTraffic: 198000,
    overlapScore: 65,
  },
  {
    id: '3',
    domain: 'competitor3.com',
    domainAuthority: 55,
    backlinks: 23400,
    organicKeywords: 18600,
    organicTraffic: 78000,
    overlapScore: 82,
  },
  {
    id: '4',
    domain: 'competitor4.com',
    domainAuthority: 61,
    backlinks: 38900,
    organicKeywords: 22400,
    organicTraffic: 95000,
    overlapScore: 71,
  },
];

export const mockReports: ReportData[] = [
  {
    id: '1',
    name: 'Monthly SEO Audit - January 2024',
    type: 'seo-audit',
    status: 'completed',
    createdAt: '2024-01-15',
    size: '2.4 MB',
    downloadUrl: '#',
  },
  {
    id: '2',
    name: 'Keyword Analysis Report',
    type: 'keyword-analysis',
    status: 'completed',
    createdAt: '2024-01-14',
    size: '1.8 MB',
    downloadUrl: '#',
  },
  {
    id: '3',
    name: 'Q4 Rank Tracking Summary',
    type: 'rank-report',
    status: 'processing',
    createdAt: '2024-01-16',
    size: '—',
  },
  {
    id: '4',
    name: 'Competitor Analysis - Batch 1',
    type: 'competitor-analysis',
    status: 'completed',
    createdAt: '2024-01-10',
    size: '4.2 MB',
    downloadUrl: '#',
  },
];

export const mockUserSettings: UserSettings = {
  email: 'john.doe@example.com',
  name: 'John Doe',
  company: 'Acme Corp',
  website: 'https://acme.com',
  notifications: {
    email: true,
    weeklyReport: true,
    rankChanges: true,
    newOpportunities: false,
  },
  preferences: {
    timezone: 'America/New_York',
    currency: 'USD',
    language: 'en',
  },
};

export const mockSubscription: SubscriptionData = {
  id: 'sub_12345',
  plan: 'professional',
  status: 'active',
  price: 99,
  billingCycle: 'monthly',
  nextBillingDate: '2024-02-15',
  features: [
    'Unlimited sites',
    '10,000 keywords',
    'Priority support',
    'API access',
    'White-label reports',
    'Team collaboration',
  ],
  limits: {
    sites: 50,
    keywords: 10000,
    reports: 500,
    apiCalls: 100000,
  },
  usage: {
    sites: 12,
    keywords: 2847,
    reports: 127,
    apiCalls: 45230,
  },
};

export const mockAdminUsers: AdminUser[] = [
  {
    id: '1',
    email: 'john.doe@example.com',
    name: 'John Doe',
    company: 'Acme Corp',
    status: 'active',
    role: 'user',
    plan: 'Professional',
    joinedAt: '2023-08-15',
    lastActive: '2024-01-16',
    sitesCount: 12,
    keywordsCount: 2847,
  },
  {
    id: '2',
    email: 'jane.smith@techcorp.com',
    name: 'Jane Smith',
    company: 'TechCorp Inc',
    status: 'active',
    role: 'user',
    plan: 'Enterprise',
    joinedAt: '2023-06-22',
    lastActive: '2024-01-15',
    sitesCount: 28,
    keywordsCount: 8540,
  },
  {
    id: '3',
    email: 'mike.wilson@startup.io',
    name: 'Mike Wilson',
    company: 'Startup.io',
    status: 'inactive',
    role: 'user',
    plan: 'Starter',
    joinedAt: '2023-11-10',
    lastActive: '2023-12-20',
    sitesCount: 3,
    keywordsCount: 450,
  },
  {
    id: '4',
    email: 'sarah.jones@agency.net',
    name: 'Sarah Jones',
    company: 'Digital Agency',
    status: 'active',
    role: 'admin',
    plan: 'Enterprise',
    joinedAt: '2023-04-05',
    lastActive: '2024-01-16',
    sitesCount: 45,
    keywordsCount: 12500,
  },
];

export const mockAdminSubscriptions: AdminSubscription[] = [
  {
    id: 'sub_12345',
    userId: '1',
    userName: 'John Doe',
    userEmail: 'john.doe@example.com',
    plan: 'Professional',
    status: 'active',
    amount: 99,
    billingCycle: 'monthly',
    startDate: '2023-08-15',
    nextBillingDate: '2024-02-15',
  },
  {
    id: 'sub_12346',
    userId: '2',
    userName: 'Jane Smith',
    userEmail: 'jane.smith@techcorp.com',
    plan: 'Enterprise',
    status: 'active',
    amount: 299,
    billingCycle: 'yearly',
    startDate: '2023-06-22',
    nextBillingDate: '2024-06-22',
  },
  {
    id: 'sub_12347',
    userId: '3',
    userName: 'Mike Wilson',
    userEmail: 'mike.wilson@startup.io',
    plan: 'Starter',
    status: 'past_due',
    amount: 29,
    billingCycle: 'monthly',
    startDate: '2023-11-10',
    nextBillingDate: '2024-01-10',
  },
];

export const mockAnalyticsData: AnalyticsData[] = [
  { date: '2024-01-01', activeUsers: 452, newUsers: 89, totalScans: 1234, totalReports: 234, revenue: 5234 },
  { date: '2024-01-02', activeUsers: 478, newUsers: 92, totalScans: 1456, totalReports: 267, revenue: 6123 },
  { date: '2024-01-03', activeUsers: 521, newUsers: 105, totalScans: 1678, totalReports: 298, revenue: 7891 },
  { date: '2024-01-04', activeUsers: 489, newUsers: 87, totalScans: 1567, totalReports: 276, revenue: 6234 },
  { date: '2024-01-05', activeUsers: 512, newUsers: 98, totalScans: 1789, totalReports: 312, revenue: 7567 },
  { date: '2024-01-06', activeUsers: 498, newUsers: 94, totalScans: 1654, totalReports: 289, revenue: 6987 },
  { date: '2024-01-07', activeUsers: 534, newUsers: 112, totalScans: 1890, totalReports: 345, revenue: 8234 },
];

export const mockNotifications: NotificationData[] = [
  {
    id: '1',
    title: 'Report Generated',
    message: 'Your monthly SEO audit report is ready for download.',
    type: 'success',
    timestamp: '2024-01-16T10:30:00Z',
    read: false,
  },
  {
    id: '2',
    title: 'Keyword Alert',
    message: '3 keywords moved up in rankings today.',
    type: 'info',
    timestamp: '2024-01-16T08:15:00Z',
    read: false,
  },
  {
    id: '3',
    title: 'Subscription Expiring',
    message: 'Your subscription renews in 7 days.',
    type: 'warning',
    timestamp: '2024-01-15T16:45:00Z',
    read: true,
  },
];

export const mockSEOAnalysisHistory: SEOAnalysisHistory[] = [
  {
    id: 'seo-1',
    url: 'https://example.com',
    crawlMode: 'FULL_CRAWL',
    score: 84,
    criticalIssues: 3,
    warnings: 12,
    passedChecks: 45,
    status: 'completed',
    createdAt: '2024-01-15T14:30:00Z',
    pageCount: 156,
  },
  {
    id: 'seo-2',
    url: 'https://techstartup.io',
    crawlMode: 'SITEMAP_ONLY',
    score: 72,
    criticalIssues: 8,
    warnings: 23,
    passedChecks: 38,
    status: 'completed',
    createdAt: '2024-01-14T10:15:00Z',
    pageCount: 45,
  },
  {
    id: 'seo-3',
    url: 'https://onlinestore.com',
    crawlMode: 'FULL_CRAWL',
    score: 0,
    criticalIssues: 0,
    warnings: 0,
    passedChecks: 0,
    status: 'processing',
    createdAt: '2024-01-16T09:00:00Z',
    pageCount: 0,
  },
  {
    id: 'seo-4',
    url: 'https://blog.platform.dev',
    crawlMode: 'SITEMAP_ONLY',
    score: 91,
    criticalIssues: 1,
    warnings: 5,
    passedChecks: 52,
    status: 'completed',
    createdAt: '2024-01-12T16:45:00Z',
    pageCount: 32,
  },
  {
    id: 'seo-5',
    url: 'https://saas-app.net',
    crawlMode: 'FULL_CRAWL',
    score: 68,
    criticalIssues: 12,
    warnings: 31,
    passedChecks: 29,
    status: 'completed',
    createdAt: '2024-01-10T11:20:00Z',
    pageCount: 89,
  },
];

export const mockKeywordResearchHistory: KeywordResearchHistory[] = [
  {
    id: 'kw-1',
    primaryKeyword: 'seo optimization tools',
    relatedKeywordsCount: 25,
    longTailKeywordsCount: 18,
    searchResultsCount: 10,
    status: 'completed',
    createdAt: '2024-01-15T12:00:00Z',
  },
  {
    id: 'kw-2',
    primaryKeyword: 'best project management software',
    relatedKeywordsCount: 32,
    longTailKeywordsCount: 24,
    searchResultsCount: 10,
    status: 'completed',
    createdAt: '2024-01-14T09:30:00Z',
  },
  {
    id: 'kw-3',
    primaryKeyword: 'content marketing strategy',
    relatedKeywordsCount: 28,
    longTailKeywordsCount: 22,
    searchResultsCount: 10,
    status: 'completed',
    createdAt: '2024-01-13T15:45:00Z',
  },
  {
    id: 'kw-4',
    primaryKeyword: 'email automation tools',
    relatedKeywordsCount: 19,
    longTailKeywordsCount: 15,
    searchResultsCount: 10,
    status: 'completed',
    createdAt: '2024-01-11T10:00:00Z',
  },
  {
    id: 'kw-5',
    primaryKeyword: 'landing page best practices',
    relatedKeywordsCount: 0,
    longTailKeywordsCount: 0,
    searchResultsCount: 0,
    status: 'processing',
    createdAt: '2024-01-16T08:00:00Z',
  },
];

export const mockRankCheckHistory: RankCheckHistory[] = [
  {
    id: 'rank-1',
    domain: 'https://example.com',
    keywords: ['seo tools', 'keyword research', 'backlink checker'],
    top10Count: 2,
    notRankingCount: 0,
    avgPosition: 8.5,
    status: 'completed',
    createdAt: '2024-01-15T14:00:00Z',
  },
  {
    id: 'rank-2',
    domain: 'https://techstartup.io',
    keywords: ['saas software', 'project management', 'team collaboration'],
    top10Count: 1,
    notRankingCount: 2,
    avgPosition: 23.7,
    status: 'completed',
    createdAt: '2024-01-14T11:30:00Z',
  },
  {
    id: 'rank-3',
    domain: 'https://onlinestore.com',
    keywords: ['online shopping', 'ecommerce platform', 'buy online'],
    top10Count: 3,
    notRankingCount: 0,
    avgPosition: 5.2,
    status: 'completed',
    createdAt: '2024-01-13T16:00:00Z',
  },
  {
    id: 'rank-4',
    domain: 'https://blog.platform.dev',
    keywords: ['web development', 'programming tutorials', 'coding tips'],
    top10Count: 0,
    notRankingCount: 1,
    avgPosition: 15.3,
    status: 'completed',
    createdAt: '2024-01-12T09:15:00Z',
  },
  {
    id: 'rank-5',
    domain: 'https://saas-app.net',
    keywords: ['business software', 'productivity tools'],
    top10Count: 0,
    notRankingCount: 0,
    avgPosition: null,
    status: 'processing',
    createdAt: '2024-01-16T10:30:00Z',
  },
];
